addons:
  postgresql: 9.2
  code_climate:
    repo_token: 915fb7899aed5496ffa2b60cb9b6f208164427996dc2cbc3cd9b2b6cece668f0
after_success:
- bundle exec codeclimate-test-reporter
dist: trusty
language: ruby
rvm:
- 2.4.1
script:
- bundle exec rails db:setup RAILS_ENV=test
deploy:
  provider: heroku
  app: tucultivo
  api_key:
    secure: "anZAwdCoo2FjNFgbNdCYzRmpGWaKsKqLJ18WT/mNBt5uMwj06rC50i2dnyJ+vqMrN0G/akkXOEu29mSkCskDt4WWSIKwnt6mKHOSxpVDaAwbK/ME3QCMFgeg223H13RI8OeE6LDtMjIfygwFY7EQlr+3ChqShwTzdqReolBYM5DZ0GwkTPhDUilDq3Ke1kJyKi4yvSYn5nGIy86Fdi9tTGkwgBMy+sXfJAfnNXwZ+u7G9jT2V24EkGm7iEnnHGzkSH2vpVcKDPrBHmA7BCAJnxNm577pn46u6pxu4Y4J+PZ2VIaiotSw7YRKQt6QO9r8Og+fk+rD7gCPjBYEv3q/CuyOCrUWAFJku3Vgpy3LHgBhGxrfHkxV1VtxOTaSjR1ikyHKPjXMZ59XX+a0WAOPxnCjM/p7KqR+E4+tA108feJPQWidE6CGhf+XZ2EnZW79gbPWdYkxy9ykvD0W6sd5VW0Mz3wBTb3DwnIvWwqSF6774/6GMJdl28qzYD7ftx3Hr+rPCDL1iI41hzDCLVAPRIiBkBYQsYNhefszoMr8GOfHxONf8dUY0ts2R1RHdDHnzk8VtRWTD9reuOVYoyhj1S3bpMRgsIENe9TmhysW59sMrpiZCjxiuO5RzH6uhzfmxxtB0aclRxHbCqUenMeaWEwmL+4LLI2HatPF5l1+SFI="  
  run: 'rake db:migrate RAILS_ENV=production'
