# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 321239a5784b42e0d3ff1cee84c94d1d087045c813bbe4ba4e69cce775d31ff90da278bdc618f40e5ae6d138cd271c93b64f6c75d351b352cdf63f13cad120d9

test:
  secret_key_base: c503f7c7d0d51054de5fce0993cbb5a160900e65b6cc7ac5e524535e1b2a8f3922aa809ee41db051cd446dabc8cada74227ee80409b2876385d3b8dcba3d67ed

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
